# -*- coding: utf-8 -*-
"""Tarea 1.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xd5ecKRHtx_Gb_OErKk5IqxLD6ZsUsyN
"""

import math

#primero defino los valores de las variables que voy a ocupar
valor_real = math.exp(1)
e = 0
n = 0
error = 1
#ahora quiero que la funcion pare cuando lleguemos a un error menor 0.01, voy aumentando el n a medida que se va haciendo la suma
while error > 0.01:
  factorial = math.factorial(n)
  e = e + 1/factorial
  error = abs(valor_real - e)
  n = n + 1
print(e)
print(error)